# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/echo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/echo.proto',
  package='',
  serialized_pb=_b('\n\x13protocol/echo.proto\"J\n\x04\x45\x63ho\x1a \n\x03Req\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0b\n\x03str\x18\x02 \x02(\t\x1a \n\x03Res\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0b\n\x03str\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ECHO_REQ = _descriptor.Descriptor(
  name='Req',
  full_name='Echo.Req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Echo.Req.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str', full_name='Echo.Req.str', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=63,
)

_ECHO_RES = _descriptor.Descriptor(
  name='Res',
  full_name='Echo.Res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Echo.Res.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='str', full_name='Echo.Res.str', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=97,
)

_ECHO = _descriptor.Descriptor(
  name='Echo',
  full_name='Echo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ECHO_REQ, _ECHO_RES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=97,
)

_ECHO_REQ.containing_type = _ECHO
_ECHO_RES.containing_type = _ECHO
DESCRIPTOR.message_types_by_name['Echo'] = _ECHO

Echo = _reflection.GeneratedProtocolMessageType('Echo', (_message.Message,), dict(

  Req = _reflection.GeneratedProtocolMessageType('Req', (_message.Message,), dict(
    DESCRIPTOR = _ECHO_REQ,
    __module__ = 'protocol.echo_pb2'
    # @@protoc_insertion_point(class_scope:Echo.Req)
    ))
  ,

  Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), dict(
    DESCRIPTOR = _ECHO_RES,
    __module__ = 'protocol.echo_pb2'
    # @@protoc_insertion_point(class_scope:Echo.Res)
    ))
  ,
  DESCRIPTOR = _ECHO,
  __module__ = 'protocol.echo_pb2'
  # @@protoc_insertion_point(class_scope:Echo)
  ))
_sym_db.RegisterMessage(Echo)
_sym_db.RegisterMessage(Echo.Req)
_sym_db.RegisterMessage(Echo.Res)


# @@protoc_insertion_point(module_scope)
