// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/Regist.proto

#ifndef PROTOBUF_msg_2fRegist_2eproto__INCLUDED
#define PROTOBUF_msg_2fRegist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_2fRegist_2eproto();
void protobuf_AssignDesc_msg_2fRegist_2eproto();
void protobuf_ShutdownFile_msg_2fRegist_2eproto();

class Regist;
class Regist_Req;
class Regist_Res;

// ===================================================================

class Regist_Req : public ::google::protobuf::Message {
 public:
  Regist_Req();
  virtual ~Regist_Req();

  Regist_Req(const Regist_Req& from);

  inline Regist_Req& operator=(const Regist_Req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Regist_Req& default_instance();

  void Swap(Regist_Req* other);

  // implements Message ----------------------------------------------

  Regist_Req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Regist_Req& from);
  void MergeFrom(const Regist_Req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 my_id = 1;
  inline bool has_my_id() const;
  inline void clear_my_id();
  static const int kMyIdFieldNumber = 1;
  inline ::google::protobuf::int32 my_id() const;
  inline void set_my_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Regist.Req)
 private:
  inline void set_has_my_id();
  inline void clear_has_my_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 my_id_;
  friend void  protobuf_AddDesc_msg_2fRegist_2eproto();
  friend void protobuf_AssignDesc_msg_2fRegist_2eproto();
  friend void protobuf_ShutdownFile_msg_2fRegist_2eproto();

  void InitAsDefaultInstance();
  static Regist_Req* default_instance_;
};
// -------------------------------------------------------------------

class Regist_Res : public ::google::protobuf::Message {
 public:
  Regist_Res();
  virtual ~Regist_Res();

  Regist_Res(const Regist_Res& from);

  inline Regist_Res& operator=(const Regist_Res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Regist_Res& default_instance();

  void Swap(Regist_Res* other);

  // implements Message ----------------------------------------------

  Regist_Res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Regist_Res& from);
  void MergeFrom(const Regist_Res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Regist.Res)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_msg_2fRegist_2eproto();
  friend void protobuf_AssignDesc_msg_2fRegist_2eproto();
  friend void protobuf_ShutdownFile_msg_2fRegist_2eproto();

  void InitAsDefaultInstance();
  static Regist_Res* default_instance_;
};
// -------------------------------------------------------------------

class Regist : public ::google::protobuf::Message {
 public:
  Regist();
  virtual ~Regist();

  Regist(const Regist& from);

  inline Regist& operator=(const Regist& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Regist& default_instance();

  void Swap(Regist* other);

  // implements Message ----------------------------------------------

  Regist* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Regist& from);
  void MergeFrom(const Regist& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Regist_Req Req;
  typedef Regist_Res Res;

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Regist)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_2fRegist_2eproto();
  friend void protobuf_AssignDesc_msg_2fRegist_2eproto();
  friend void protobuf_ShutdownFile_msg_2fRegist_2eproto();

  void InitAsDefaultInstance();
  static Regist* default_instance_;
};
// ===================================================================


// ===================================================================

// Regist_Req

// required int32 my_id = 1;
inline bool Regist_Req::has_my_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Regist_Req::set_has_my_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Regist_Req::clear_has_my_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Regist_Req::clear_my_id() {
  my_id_ = 0;
  clear_has_my_id();
}
inline ::google::protobuf::int32 Regist_Req::my_id() const {
  // @@protoc_insertion_point(field_get:Regist.Req.my_id)
  return my_id_;
}
inline void Regist_Req::set_my_id(::google::protobuf::int32 value) {
  set_has_my_id();
  my_id_ = value;
  // @@protoc_insertion_point(field_set:Regist.Req.my_id)
}

// -------------------------------------------------------------------

// Regist_Res

// required int32 code = 1;
inline bool Regist_Res::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Regist_Res::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Regist_Res::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Regist_Res::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 Regist_Res::code() const {
  // @@protoc_insertion_point(field_get:Regist.Res.code)
  return code_;
}
inline void Regist_Res::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:Regist.Res.code)
}

// -------------------------------------------------------------------

// Regist


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2fRegist_2eproto__INCLUDED
