// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/Regist.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg/Regist.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Regist_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Regist_reflection_ = NULL;
const ::google::protobuf::Descriptor* Regist_Req_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Regist_Req_reflection_ = NULL;
const ::google::protobuf::Descriptor* Regist_Res_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Regist_Res_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_2fRegist_2eproto() {
  protobuf_AddDesc_msg_2fRegist_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg/Regist.proto");
  GOOGLE_CHECK(file != NULL);
  Regist_descriptor_ = file->message_type(0);
  static const int Regist_offsets_[1] = {
  };
  Regist_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Regist_descriptor_,
      Regist::default_instance_,
      Regist_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Regist));
  Regist_Req_descriptor_ = Regist_descriptor_->nested_type(0);
  static const int Regist_Req_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist_Req, my_id_),
  };
  Regist_Req_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Regist_Req_descriptor_,
      Regist_Req::default_instance_,
      Regist_Req_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist_Req, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist_Req, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Regist_Req));
  Regist_Res_descriptor_ = Regist_descriptor_->nested_type(1);
  static const int Regist_Res_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist_Res, code_),
  };
  Regist_Res_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Regist_Res_descriptor_,
      Regist_Res::default_instance_,
      Regist_Res_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist_Res, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Regist_Res, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Regist_Res));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_2fRegist_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Regist_descriptor_, &Regist::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Regist_Req_descriptor_, &Regist_Req::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Regist_Res_descriptor_, &Regist_Res::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_2fRegist_2eproto() {
  delete Regist::default_instance_;
  delete Regist_reflection_;
  delete Regist_Req::default_instance_;
  delete Regist_Req_reflection_;
  delete Regist_Res::default_instance_;
  delete Regist_Res_reflection_;
}

void protobuf_AddDesc_msg_2fRegist_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020msg/Regist.proto\"3\n\006Regist\032\024\n\003Req\022\r\n\005m"
    "y_id\030\001 \002(\005\032\023\n\003Res\022\014\n\004code\030\001 \002(\005", 71);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg/Regist.proto", &protobuf_RegisterTypes);
  Regist::default_instance_ = new Regist();
  Regist_Req::default_instance_ = new Regist_Req();
  Regist_Res::default_instance_ = new Regist_Res();
  Regist::default_instance_->InitAsDefaultInstance();
  Regist_Req::default_instance_->InitAsDefaultInstance();
  Regist_Res::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_2fRegist_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_2fRegist_2eproto {
  StaticDescriptorInitializer_msg_2fRegist_2eproto() {
    protobuf_AddDesc_msg_2fRegist_2eproto();
  }
} static_descriptor_initializer_msg_2fRegist_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Regist_Req::kMyIdFieldNumber;
#endif  // !_MSC_VER

Regist_Req::Regist_Req()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Regist.Req)
}

void Regist_Req::InitAsDefaultInstance() {
}

Regist_Req::Regist_Req(const Regist_Req& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Regist.Req)
}

void Regist_Req::SharedCtor() {
  _cached_size_ = 0;
  my_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Regist_Req::~Regist_Req() {
  // @@protoc_insertion_point(destructor:Regist.Req)
  SharedDtor();
}

void Regist_Req::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Regist_Req::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Regist_Req::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Regist_Req_descriptor_;
}

const Regist_Req& Regist_Req::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2fRegist_2eproto();
  return *default_instance_;
}

Regist_Req* Regist_Req::default_instance_ = NULL;

Regist_Req* Regist_Req::New() const {
  return new Regist_Req;
}

void Regist_Req::Clear() {
  my_id_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Regist_Req::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Regist.Req)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 my_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &my_id_)));
          set_has_my_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Regist.Req)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Regist.Req)
  return false;
#undef DO_
}

void Regist_Req::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Regist.Req)
  // required int32 my_id = 1;
  if (has_my_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->my_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Regist.Req)
}

::google::protobuf::uint8* Regist_Req::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Regist.Req)
  // required int32 my_id = 1;
  if (has_my_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->my_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Regist.Req)
  return target;
}

int Regist_Req::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 my_id = 1;
    if (has_my_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->my_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Regist_Req::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Regist_Req* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Regist_Req*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Regist_Req::MergeFrom(const Regist_Req& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_my_id()) {
      set_my_id(from.my_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Regist_Req::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Regist_Req::CopyFrom(const Regist_Req& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Regist_Req::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Regist_Req::Swap(Regist_Req* other) {
  if (other != this) {
    std::swap(my_id_, other->my_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Regist_Req::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Regist_Req_descriptor_;
  metadata.reflection = Regist_Req_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Regist_Res::kCodeFieldNumber;
#endif  // !_MSC_VER

Regist_Res::Regist_Res()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Regist.Res)
}

void Regist_Res::InitAsDefaultInstance() {
}

Regist_Res::Regist_Res(const Regist_Res& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Regist.Res)
}

void Regist_Res::SharedCtor() {
  _cached_size_ = 0;
  code_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Regist_Res::~Regist_Res() {
  // @@protoc_insertion_point(destructor:Regist.Res)
  SharedDtor();
}

void Regist_Res::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Regist_Res::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Regist_Res::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Regist_Res_descriptor_;
}

const Regist_Res& Regist_Res::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2fRegist_2eproto();
  return *default_instance_;
}

Regist_Res* Regist_Res::default_instance_ = NULL;

Regist_Res* Regist_Res::New() const {
  return new Regist_Res;
}

void Regist_Res::Clear() {
  code_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Regist_Res::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Regist.Res)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 code = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
          set_has_code();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Regist.Res)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Regist.Res)
  return false;
#undef DO_
}

void Regist_Res::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Regist.Res)
  // required int32 code = 1;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Regist.Res)
}

::google::protobuf::uint8* Regist_Res::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Regist.Res)
  // required int32 code = 1;
  if (has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Regist.Res)
  return target;
}

int Regist_Res::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 code = 1;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->code());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Regist_Res::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Regist_Res* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Regist_Res*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Regist_Res::MergeFrom(const Regist_Res& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_code()) {
      set_code(from.code());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Regist_Res::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Regist_Res::CopyFrom(const Regist_Res& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Regist_Res::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void Regist_Res::Swap(Regist_Res* other) {
  if (other != this) {
    std::swap(code_, other->code_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Regist_Res::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Regist_Res_descriptor_;
  metadata.reflection = Regist_Res_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
#endif  // !_MSC_VER

Regist::Regist()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Regist)
}

void Regist::InitAsDefaultInstance() {
}

Regist::Regist(const Regist& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Regist)
}

void Regist::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Regist::~Regist() {
  // @@protoc_insertion_point(destructor:Regist)
  SharedDtor();
}

void Regist::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Regist::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Regist::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Regist_descriptor_;
}

const Regist& Regist::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_2fRegist_2eproto();
  return *default_instance_;
}

Regist* Regist::default_instance_ = NULL;

Regist* Regist::New() const {
  return new Regist;
}

void Regist::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Regist::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Regist)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:Regist)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Regist)
  return false;
#undef DO_
}

void Regist::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Regist)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Regist)
}

::google::protobuf::uint8* Regist::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Regist)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Regist)
  return target;
}

int Regist::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Regist::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Regist* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Regist*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Regist::MergeFrom(const Regist& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Regist::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Regist::CopyFrom(const Regist& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Regist::IsInitialized() const {

  return true;
}

void Regist::Swap(Regist* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Regist::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Regist_descriptor_;
  metadata.reflection = Regist_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
