// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg/Shutdown.proto

#ifndef PROTOBUF_msg_2fShutdown_2eproto__INCLUDED
#define PROTOBUF_msg_2fShutdown_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_2fShutdown_2eproto();
void protobuf_AssignDesc_msg_2fShutdown_2eproto();
void protobuf_ShutdownFile_msg_2fShutdown_2eproto();

class Shutdown;
class Shutdown_Req;
class Shutdown_Res;

// ===================================================================

class Shutdown_Req : public ::google::protobuf::Message {
 public:
  Shutdown_Req();
  virtual ~Shutdown_Req();

  Shutdown_Req(const Shutdown_Req& from);

  inline Shutdown_Req& operator=(const Shutdown_Req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Shutdown_Req& default_instance();

  void Swap(Shutdown_Req* other);

  // implements Message ----------------------------------------------

  Shutdown_Req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Shutdown_Req& from);
  void MergeFrom(const Shutdown_Req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Shutdown.Req)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_msg_2fShutdown_2eproto();
  friend void protobuf_AssignDesc_msg_2fShutdown_2eproto();
  friend void protobuf_ShutdownFile_msg_2fShutdown_2eproto();

  void InitAsDefaultInstance();
  static Shutdown_Req* default_instance_;
};
// -------------------------------------------------------------------

class Shutdown_Res : public ::google::protobuf::Message {
 public:
  Shutdown_Res();
  virtual ~Shutdown_Res();

  Shutdown_Res(const Shutdown_Res& from);

  inline Shutdown_Res& operator=(const Shutdown_Res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Shutdown_Res& default_instance();

  void Swap(Shutdown_Res* other);

  // implements Message ----------------------------------------------

  Shutdown_Res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Shutdown_Res& from);
  void MergeFrom(const Shutdown_Res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Shutdown.Res)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_msg_2fShutdown_2eproto();
  friend void protobuf_AssignDesc_msg_2fShutdown_2eproto();
  friend void protobuf_ShutdownFile_msg_2fShutdown_2eproto();

  void InitAsDefaultInstance();
  static Shutdown_Res* default_instance_;
};
// -------------------------------------------------------------------

class Shutdown : public ::google::protobuf::Message {
 public:
  Shutdown();
  virtual ~Shutdown();

  Shutdown(const Shutdown& from);

  inline Shutdown& operator=(const Shutdown& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Shutdown& default_instance();

  void Swap(Shutdown* other);

  // implements Message ----------------------------------------------

  Shutdown* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Shutdown& from);
  void MergeFrom(const Shutdown& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Shutdown_Req Req;
  typedef Shutdown_Res Res;

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Shutdown)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_msg_2fShutdown_2eproto();
  friend void protobuf_AssignDesc_msg_2fShutdown_2eproto();
  friend void protobuf_ShutdownFile_msg_2fShutdown_2eproto();

  void InitAsDefaultInstance();
  static Shutdown* default_instance_;
};
// ===================================================================


// ===================================================================

// Shutdown_Req

// required int32 code = 1;
inline bool Shutdown_Req::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Shutdown_Req::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Shutdown_Req::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Shutdown_Req::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 Shutdown_Req::code() const {
  // @@protoc_insertion_point(field_get:Shutdown.Req.code)
  return code_;
}
inline void Shutdown_Req::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:Shutdown.Req.code)
}

// -------------------------------------------------------------------

// Shutdown_Res

// required int32 code = 1;
inline bool Shutdown_Res::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Shutdown_Res::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Shutdown_Res::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Shutdown_Res::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 Shutdown_Res::code() const {
  // @@protoc_insertion_point(field_get:Shutdown.Res.code)
  return code_;
}
inline void Shutdown_Res::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:Shutdown.Res.code)
}

// -------------------------------------------------------------------

// Shutdown


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2fShutdown_2eproto__INCLUDED
